### ISSUE TITLE
Improvements for Continuous Koopman

### ISSUE THREAD

**Issue by EthanJamesLew** [EthanJamesLew/AutoKoopman#82]
From meeting 02/23
- [ ] Reset at every step
- [ ] Simulate using just the $A$ and $B$ matrices
- [ ] Adaptive step

Look into the accuracy here--the fit is suspect.

This is needed for the reachability work.

CC @Abdu-Hekal

**Comment by Abdu-Hekal** [comment]
@EthanJamesLew Continuous Koopman works well for systems with no inputs but seems to suffer for systems with inputs. For example in the autokoopman-introduction notebook and for the PendulumWithInput benchmark. These two figures show the difference between discrete and continuous learning, with the worse fit for continuous learning. Could this potentially be due to a mismatch in input step and system step which isn't handled well by continuous learning?
 
<img width="698" alt="Screenshot 2024-03-25 at 15 27 58" src="https://github.com/EthanJamesLew/AutoKoopman/assets/91421619/d4a6d1c8-4630-4919-91c7-0d74d8678833">
<img width="691" alt="Screenshot 2024-03-25 at 15 29 08" src="https://github.com/EthanJamesLew/AutoKoopman/assets/91421619/8103e45a-bab8-497f-9783-0c1ea6ed1e10">

**Comment by EthanJamesLew** [comment]
closing for now
